env:
  - LIBWS_METHOD=coverage LIBWS_EXTRA_ARGS="-DLIBWS_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug" LIBWS_EXTRA_INSTALL="valgrind lcov"
language: C
compiler:
  - gcc
  - clang
before_install:
  - sudo pip install cpp-coveralls --use-mirrors
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq cmake $LIBWS_EXTRA_INSTALL 
script:
  if [ "$LIBWS_METHOD" = "coverage" ]; then mkdir build && cd build && cmake $LIBWS_EXTRA_ARGS .. && cmake --build . && ctest --output-on-failure; fi
after_success:
  - CI=true TRAVIS=true coveralls -n -b build/ --verbose
