env:
  - LIBWS_METHOD=coverage CMAKE_ARGS="-DLIBWS_WITH_MEMCHECK=OFF -DLIBWS_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug" COVERALLS=yes
  - LIBWS_METHOD=memcheck
  - LIBWS_METHOD=autobahn CMAKE_ARGS="-DLIBWS_WITH_AUTOBAHN=ON"
language: c
compiler:
  - gcc
  - clang
install:
  - if [ x$LIBWS_METHOD == xcoverage ]; then sudo pip install cpp-coveralls; fi
  - if [ x$LIBWS_METHOD == xcoverage ]; then sudo apt-get update -qq && sudo apt-get install -y -qq lcov valgrind; fi
  - if [ x$LIBWS_METHOD == xmemcheck ]; then sudo apt-get update -qq && sudo apt-get install -y -qq lcov valgrind; fi
  - if [ x$LIBWS_METHOD == xautobahn ]; then sudo pip install autobahntestsuite; fi
script:
  - if [ x$LIBWS_METHOD == xcoverage ]; then cmake $CMAKE_ARGS . && cmake --build . && ctest --output-on-failure; fi
  - if [ x$LIBWS_METHOD == xmemcheck ]; then mkdir build && cd build && cmake $CMAKE_ARGS .. && cmake --build . && ctest --output-on-failure; fi
  - if [ x$LIBWS_METHOD == xautobahn ]; then sh -c ./.travis-ci-autobahn.sh; fi
after_success:
  - if [ x$COVERALLS == xyes ]; then coveralls -x c --exclude test --exclude examples --exclude-pattern 'CMake.*?\.c' --exclude-pattern 'CMake.*?\.cpp' --exclude-pattern '.*?\.h'; fi
